pub mod auth;
pub mod compact_time;
mod http_fetcher;
pub mod password;
pub use http_fetcher::HttpFetcher;
mod catalog_refresh;
mod check_in;
mod episode_still;
mod job_loop;
mod jobs_api;
mod open_coverage;
pub(crate) mod scrape_config;
pub(crate) mod scrape_metadata;
pub mod scrape_store;
pub mod ssdp;
mod subscribe_create;
mod watch_intake;
mod watch_ledger;
mod watch_scrape;
pub mod worker;
pub use scrape_store::ScrapeStoreExt;
mod admit;
pub mod auto_resolve;
pub mod bootstrap_credentials;
pub mod catalog;
mod catalog_cache;
mod catalog_fanout;
mod claim;
mod delivery;
pub mod directory;
mod dynamic_downloader;
pub mod fingerprint_job;
pub mod http;
pub mod management;
pub mod marker_resolver;
pub mod media_posters;
pub mod media_server_provider;
mod poster;
mod poster_fetch;
mod runtime_downloader;
pub mod settings_keys;
pub mod store;
pub mod theintrodb;
pub mod ui;
pub use poster_fetch::PosterFetch;
pub mod anilist_http;
pub mod bangumi_http;
pub mod cli;
pub mod config;
pub mod douban_http;
pub mod fs_watcher;
#[cfg(test)]
mod fs_watcher_tests;
pub mod http_agent;
pub mod obscura_manager;
pub mod probe_manager;
pub mod system_logs;
pub mod tmdb_http;
pub mod tvdb_http;
pub mod user_agent;

pub use config::ServerConfig;
pub use dynamic_downloader::DynamicDownloader;
pub use fs_watcher::spawn_fs_watcher;
pub use job_loop::{spawn_job_loop, spawn_job_loop_with};
pub use management::{ApiState, router};
pub use runtime_downloader::{ChosenDownloader, DownloaderEnv, choose_downloader};
pub use store::Store;
